Reverse has one
laravel/nova-dusk-suite pull request #41
Opened 2020-10-30 11:54 UTC by anditsung

add relation to test HasOne field

2020-10-30 15:54 UTC, crynobone requested changes

2020-10-30 15:54 UTC, crynobone commented on database/migrations/2018_07_16_180920_create_addresses_table.php
> +            $table->unsignedInteger('user_id');
This going to break other tests which doesn't expect to set `user_id` when testing address.

2020-10-30 15:54 UTC, crynobone commented on app/Nova/Address.php
> +            BelongsTo::make('user', 'user', User::class),
Should be optional. Otherwise might be best to create new resources and models to demonstrate the usage.

2020-10-31 00:52 UTC, anditsung commented
got it. will create a new resource and model for this test

2020-10-31 04:04 UTC, anditsung commented
hi, i already create new resource and model

2020-11-02 00:03 UTC, merged